<?xml version="1.0" encoding="utf-8"?><Database Name="practice" Class="modelClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-ACSKR3S\BAPI6655;Initial Catalog=practice;Persist Security Info=True;User ID=bapi6655" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="practiceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.purchaseAdvice" Member="purchaseAdvices">
    <Type Name="purchaseAdvice">
      <Column Name="PostId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="brokerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="emaill" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="createdon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="createdby" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>